### ISSUE TITLE
Intentional use of min version?

### ISSUE THREAD

**Issue by diversity-co-uk** [janeczku/docker-alpine-kubernetes#1]
Hi,

The docker file currently references the min version of go-dnsmasq. This has the effect of disabling caching.

With the non-min version used instead, the environment variable DNSMASQ_RCACHE can be used to provide a non-zero cache size to enable caching. This is useful in my use-case: Make a light weight DNS caching server for a local network (larger than just the docker host), with hosts added via --add-host <host>:<ip> in the docker run invocation.

Perhaps this is not useful in the intended use-case of kubernetes support.

**Comment by janeczku** [comment]
Hi @diversity-co-uk, the purpose of the kubernetes image is to provide a local DNS server for processes running inside the container.
If you want to provide DNS services to a local network you can use this Docker image that comes with the full version of go-dnsmasq:
https://hub.docker.com/r/janeczku/go-dnsmasq/

**Comment by diversity-co-uk** [comment]
Thanks. Understood. [ the forward to go-dnsmasq for doc threw me off ]

**Comment by janeczku** [comment]
@diversity-co-uk no problem. Feedback is welcome. Please report on the https://github.com/janeczku/go-dnsmasq repository.
