### ISSUE TITLE
Do recent Musl changes fix DNS issue?

### ISSUE THREAD

**Issue by azell** [janeczku/docker-alpine-kubernetes#4]
FYI: http://git.musl-libc.org/cgit/musl/commit/?id=3d6e2e477ced37fd328870f018950b283cb7293c

> add support for search domains to dns resolver
> search is only performed if the search or domain keyword is used in
> resolv.conf and the queried name has fewer than ndots dots. there is
> no default domain and names with >=ndots dots are never subjected to
> search; failure in the root scope is final.
> 
> the (non-POSIX) res_search API presently does not honor search. this
> may be added at some point in the future if needed.
> 
> resolv.conf is now parsed twice, at two different layers of the code
> involved. this will be fixed in a subsequent patch.

Does this potentially remove the need for a separate DNS resolver?

**Comment by janeczku** [comment]
Thanks for sharing this! Good news indeed.
As to your question: If you are strictly using single-label names for service discovery then i expect the  musl search implementation to work perfectly fine. Apparently they decided to drop search alltogether when the query has >= ndots. This means we still cannot expect it to behave like GNU libc distributions. For example, traversing namespaces in Kubernetes (`<service-name>.<namespace-name>.svc.cluster.local`) won't work  unless you set `ndots` option to 5 (which is a really bad idea for a number of reasons).

**Comment by janeczku** [comment]
No issue here, so closing.
