### ISSUE TITLE
Services.d not reliably starting up on Kubernetes. 

### ISSUE THREAD

**Issue by andrewhowdencom** [janeczku/docker-alpine-kubernetes#5]
Hello, 

Having a little trouble getting an NGINX container built on alpine-linux to start on Kubernetes. Dockerfile is at the URL below:

https://github.com/andrewhowdencom/docker-nginx/blob/ahowden_rebuild-on-alpine/Dockerfile

Used as the base for
https://github.com/andrewhowdencom/m2onk8s/blob/master/package/build/docker/nginx/Dockerfile

Kubernetes RC configuration is here: https://github.com/andrewhowdencom/m2onk8s/blob/master/package/build/kubernetes/magento-rc.json

Logs from 
$ kubectl logs {pod} -c {container} -p 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-resolver-logdir: executing... 
[cont-init.d] 01-resolver-logdir: exited 0.
[cont-init.d] done.
[services.d] starting services
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Importantly, the services.d call never finishes. 
From local on the Kubernetes node (and invoked by Docker):

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-resolver-logdir: executing... 
[cont-init.d] 01-resolver-logdir: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Still looking into why, but heads up! If I work out it's something stupid I've done, I'll close this.

**Comment by andrewhowdencom** [comment]
The super weird part is one container in the pod always starts, and it's not always the same container. At the moment my thinking is maybe services.d is starting something that builds on the same port as services.d in another container, which being in the same pod, craps out -- I think they share the same address space within the pod.

**Comment by janeczku** [comment]
@andrewhowdencom 
Hi Andrew, the log indicate that the resolver service fails to start. I recently changed it so that the service logs to a file instead to stdout - probably not the best idea for debugging purposes...
Is there anyway you can get the logfile at `/var/log/go-dnsmasq` from a failing container?

Something along:

> docker export -o export.tar CONTAINER_ID
> tar --extract --file=export.tar var/log/go-dnsmasq
> cat ./var/log/go-dnsmasq

**Comment by andrewhowdencom** [comment]
2016-02-05 09:24:41.354069500  level=info msg="Starting go-dnsmasq server 0.9.8 ..." 
2016-02-05 09:24:41.354116500  level=info msg="Search domains in use: [default.svc.cluster.local. svc.cluster.local. cluster.local. c.m2onk8s.internal. google.internal.]" 
2016-02-05 09:24:41.354275500  level=info msg="Ready for queries on tcp://127.0.0.1:53 - Nameservers: [127.0.0.1:53]" 
2016-02-05 09:24:41.354301500  level=info msg="Ready for queries on udp://127.0.0.1:53 - Nameservers: [127.0.0.1:53]" 
*_2016-02-05 09:24:41.354367500  level=fatal msg="listen udp 127.0.0.1:53: bind: address already in use" 
*_

https://github.com/kubernetes/kubernetes/blob/master/docs/design/networking.md#container-to-container

> All containers within a pod behave as if they are on the same host with regard to networking. They can all reach each other’s ports on localhost.

I don't know well enough what go-dnsmasq does to say whether it's worth trying to resolve. It looks like you can only run one per pod?

Edit: I'm going to resolve this for now by splitting up the pod.

**Comment by janeczku** [comment]
FYI, with the latest version you can have one container in the Pod run go-dnsmasq as usual but disable the service for the other containers by passing the env var `ALPINE_NO_RESOLVER` with a value of `True`. The primary nameserver for these containers will still be set to localhost, hence they will use the DNS server of the sibling container.

#### Example:

``` YAML
apiVersion: v1
kind: Pod
metadata:
  name: redis_django
  labels:
    app: web
spec:
  containers:
    - name: key-value-store
      image: alpine-kubernetes-redis
      ports:
        - containerPort: 6379
    - name: frontend
      image: alpine-kubernetes-django
      ports:
        - containerPort: 8000
      env:
        - name: ALPINE_NO_RESOLVER
          value: True
```

**Comment by janeczku** [comment]
Fixed in https://github.com/janeczku/docker-alpine-kubernetes/commit/0a4e5a1b8f38611761f513f614b2ea241764e986

**Comment by andrewhowdencom** [comment]
Couldn't find a better way to thank you than to comment on this. Thanks!
