### ISSUE TITLE
go-dnsmasq append flag breaks upstream docker run commands

### ISSUE THREAD

**Issue by CheRuisiBesares** [janeczku/docker-alpine-kubernetes#9]
Hey I was doing some work on the upstream opentsdb docker image that lives here https://github.com/PeterGrace/opentsdb-docker . I noticed when I tried to rebuild it after my updates that it breaks because the version of go-dnsmasq slipped up in version from 1.0.0 to 1.0.5 in the janeczku/alpine-kubernetes:3.2 image. Looking at go-dnsmasq it looks like there were some changes to the way that this lib handles the `--append-search-domains` flag. It seems now it checks that there is at least one search domain in the resolv.conf erroring out with `FATA[0000] You need to specify some search domains`. This shouldn't be an issue in production where this is defined by default but its breaking local development for docker-machine users/users without a search domain specified. I know you can append `--dns-search` to the docker run command but I don't think that it is clear why that is needed when you first run into that error and it also breaks existing development environments.

I was wondering how you think I should proceed here. Im guessing we could relax the requirement for go-dnsmasq to have more than one search domain in order to do the append. Or we could update the entrypoint maybe to check for the existence of a search domain in the resolv.conf and put that flag on conditionally. Im going to put a pull request up in @PeterGrace's repo in just a bit. Im not sure that it will get merged in but Id like to know that the tsdb box will have a path forward as deps under it change a little.

Thanks for the awesome work. Let me know how I can help.

**Comment by janeczku** [comment]
Thanks for bringing this to me. I guess it makes a lot of sense to spit out a warning (for those running it in the shell) instead of exiting in this scenario. I will cut a new release tomorrow.

**Comment by janeczku** [comment]
append-search-domains is overridden to false and a warning logged when no search domains are configured: https://github.com/janeczku/go-dnsmasq/commit/f0260cbe1e5dca4f303d11bbe0a9c81865c21960

**Comment by PeterGrace** [comment]
Sorry to comment on a closed issue, but will the dnsmasq change go into 3.2 or do I have to switch my image to the latest tag on your alpine-kubernetes repo to receive the updates? (cc @CheRuisiBesares, thanks for bringing this to my attention)

**Comment by janeczku** [comment]
@PeterGrace NP. The automated build on Docker Hub always builds both `3.2` and `3.3` images from the current release.

**Comment by janeczku** [comment]
I will tag the new release tomorrow.
